### ISSUE TITLE
Flux not triggered by Minio bucket (Minikube single cluster)

### ISSUE THREAD

**Issue by sebastienblanc** [syntasso/kratix#16]
Hi ! 

I'm playing with Kratix, using the single cluster instructions. I tried out the jenkins example, the promise get installed, the request is applied  , the pipeline run successfully but then nothing happen. I can see in the minio pod (in '/data') that the output is written but it looks like that flux never picks it up. 
I also tried with a custom promise, same result. 
Any idea ? 
I'm on Mac ARM (M1) , minikube v1.28.0 with Docker driver.

**Comment by sebastienblanc** [comment]
I have the same behaviour using a multi cluster (using kind and your './scripts/quick-start.sh' script), could the problem be MinIO ?

**Comment by sebastienblanc** [comment]
Okay, I think it's a problem on my side with my custom promise that breaks all the rest. It might be 'cert-manager' messing things up. Will update on this hopefully tomorrow

**Comment by sebastienblanc** [comment]
Ok sorry for the noise, it turned out that I had to add `namespace: default` to my output yaml otherwise Kustomize goes crazy ... At least it's working now

**Comment by aclevername** [comment]
Thanks for opening the issue @sebastienblanc. I'm glad you managed to resolve the issue.

> Ok sorry for the noise, it turned out that I had to add namespace: default to my output yaml otherwise Kustomize goes crazy ... At least it's working now

This is a common issue that creeps up unfortunately, I think it will be worth us adding some docs to the on how to debug this sort of issue! Thanks for raising it. 

Just to explain what I think is happening is that Kratix is pushing the resources from the Promise to the MinIO bucket and at that point Kratix's work is done. Flux is the GitOps agent running on the worker cluster that is responsible for reconciling the state and it has a lot of opinions about what structure the resources should be, including that every resource *must* specify the namespace. It won't assume default if its unspecified which differs from the traditional kubectl experience, it also won't create the namespace if it doesn't exist. I believe it is possible to[ toggle this off on Flux](https://fluxcd.io/flux/components/kustomize/kustomization/#writing-a-kustomization-spec) (I believe this wasn't the default behaviour on previous versions) and this may differ with other GitOps agents like ArgoCD. I think however for best practises always specifying the namespace is every resource is the best pattern.

> Okay, I think it's a problem on my side with my custom promise that breaks all the rest.

This is another issue thats on a radar! The `quick-start` only ever sets up one `Kustomization` on the worker cluster to pull in *all* the resource, so one invalid Promise prevents all other resources from being scheduled since Flux takes an all-or-nothing approach to apply the resources. We are thinking about adjusting how the worker cluster is configured so that Kratix creates granular `Kustomization` resources per Promise, preventing one broken Promise affecting the others. Curious what your thoughts on this potential fix would be? Thanks 😄

**Comment by sebastienblanc** [comment]
@aclevername Hi ! Thx for the detailed explanation and this confirms more or less what I was suspecting :) 
For more granular Kustomization resources, I don't know enough about Flux but for instance in ArgoCD you have the concept of an `Application` that encapsulate all the resources for a particular "project", if you could do the same for Flux and have each promise in a application that could make it more resilient.

**Comment by aclevername** [comment]
>  I don't know enough about Flux but for instance in ArgoCD you have the concept of an `Application` that encapsulate all the resources for a particular "project", if you could do the same for Flux and have each promise in a application that could make it more resilient.

A Flux `Kustomization` is very similar to an `Application` in Argo from what I understand so thats useful feedback, thanks!

**Comment by aclevername** [comment]
Going to close this issue out as we have noted down some actions on our side to improve Kratix. Feel free to re-open if needed 😄
